---
# STIG: RHEL-07-010220 - Passwords for new users must be restricted to a 60-day maximum lifetime.
# description: Any password, no matter how complex, can eventually be cracked. Therefore, passwords need to be changed periodically. If the operating system does not limit the lifetime of passwords and force users to change their passwords, there is the risk that the operating system passwords could be compromised.
# severity: 'medium'
# checkid: 'C-RHEL-07-010220_chk'
# fixid: 'F-RHEL-07-010220_fix'
# version: 'RHEL-07-010220'
# ruleid: 'RHEL-07-010220_rule'
# fixtext: 'Configure the operating system to enforce a 60-day maximum password lifetime restriction.
#
#Add the following line in /etc/login.defs (or modify the line to have the required value):
#
#PASS_MAX_DAYS     60'
# checktext: 'Verify the operating system enforces a 60-day maximum password lifetime restriction for new user accounts.
#
#Check for the value of “PASS_MAX_DAYS” in /etc/login.defs with the following command:
#
## grep -i pass_max_days /etc/login.defs
#PASS_MAX_DAYS     60
#
#If the “PASS_MAX_DAYS” parameter value is not 60 or less, or is commented out, this is a finding.'

- debug: msg="rhel_07_010220 not implemented"

