---
# STIG: RHEL-07-020000 - The rsh-server package must not be installed.
# description: It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives. These unnecessary capabilities or services are often overlooked and therefore may remain unsecured. They increase the risk to the platform by providing additional attack vectors.  Operating systems are capable of providing a wide variety of functions and services. Some of the functions and services, provided by default, may not be necessary to support essential organizational operations (e.g., key missions, functions).  The rsh-server service provides an unencrypted remote access service that does not provide for the confidentiality and integrity of user passwords or the remote session and has very weak authentication.  If a privileged user were to log on using this service, the privileged user password could be compromised.
# severity: 'high'
# checkid: 'C-RHEL-07-020000_chk'
# fixid: 'F-RHEL-07-020000_fix'
# version: 'RHEL-07-020000'
# ruleid: 'RHEL-07-020000_rule'
# fixtext: 'Configure the operating system to disable non-essential capabilities by removing the rsh-server package from the system with the following command:
#
## yum remove rsh-server'
# checktext: 'Check to see if the rsh-server package is installed with the following command:
#
## yum list installed | grep rsh-server
#
#If the rsh-server package is installed, this is a finding.'

- debug: msg="rhel_07_020000 not implemented"

