---
# STIG: RHEL-07-010240 - Passwords must be prohibited from reuse for a minimum of five generations.
# description: Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks. If the information system or application allows the user to consecutively reuse their password when that password has exceeded its defined lifetime, the end result is a password that is not changed per policy requirements.
# severity: 'medium'
# checkid: 'C-RHEL-07-010240_chk'
# fixid: 'F-RHEL-07-010240_fix'
# version: 'RHEL-07-010240'
# ruleid: 'RHEL-07-010240_rule'
# fixtext: 'Configure the operating system to prohibit password reuse for a minimum of five generations.
#
#Add the following line in /etc/pam.d/system-auth (or modify the line to have the required value):
#
#password sufficient pam_unix.so use_authtok sha512 shadow remember=5'
# checktext: 'Verify the operating system prohibits password reuse for a minimum of five generations.
#
#Check for the value of the “remember” argument in /etc/pam.d/system-auth with the following command:
#
## grep -i remember /etc/pam.d/system-auth
#password sufficient pam_unix.so use_authtok sha512 shadow remember=5
#
#If the line containing the pam_unix.so line does not have the “remember” module argument set, or the value of the “remember” module argument is set to less than “5”, this is a finding.'

- debug: msg="rhel_07_010240 not implemented"

