---
# STIG: RHEL-07-040334 - The SSH daemon must not allow authentication using rhosts authentication.
# description: Configuring this setting for the SSH daemon provides additional assurance that remote logon via SSH will require a password, even in the event of misconfiguration elsewhere.
# severity: 'medium'
# checkid: 'C-RHEL-07-040334_chk'
# fixid: 'F-RHEL-07-040334_fix'
# version: 'RHEL-07-040334'
# ruleid: 'RHEL-07-040334_rule'
# fixtext: 'Configure the SSH daemon to not allow authentication using known hosts authentication.
#
#Add the following line in "/etc/ssh/sshd_config", or uncomment the line and set the value to “yes”:
#
#IgnoreRhosts yes'
# checktext: 'Verify the SSH daemon does not allow authentication using known hosts authentication.
#
#To determine how the SSH daemon\'s "IgnoreRhosts" option is set, run the following command:
#
## grep -i IgnoreRhosts /etc/ssh/sshd_config
#
#IgnoreRhosts yes
#
#If the value is returned as “no”, the returned line is commented out, or no output is returned, this is a finding.'

- debug: msg="rhel_07_040334 not implemented"

