---
# STIG: RHEL-07-030351 - The operating system must immediately notify the System Administrator (SA) and Information System Security Officer (ISSO) (at a minimum) via email when the threshold for the repository maximum audit record storage capacity is reached.
# description: If security personnel are not notified immediately when the threshold for the repository maximum audit record storage capacity is reached, they are unable to expand the audit record storage capacity before records are lost.
# severity: 'medium'
# checkid: 'C-RHEL-07-030351_chk'
# fixid: 'F-RHEL-07-030351_fix'
# version: 'RHEL-07-030351'
# ruleid: 'RHEL-07-030351_rule'
# fixtext: 'Configure the operating system to immediately notify the SA and ISSO (at a minimum) when the threshold for the repository maximum audit record storage capacity is reached.
#
#Uncomment or edit the “space_left_action” keyword in /etc/audit/auditd.conf and set it to email. 
# 
#space_left_action = email'
# checktext: 'Verify the operating system immediately notifies the SA and ISSO (at a minimum) via email when the allocated audit record storage volume reaches 75 percent of the repository maximum audit record storage capacity.
#
#Check what action the operating system takes when the threshold for the repository maximum audit record storage capacity is reached with the following command:
#
## grep -I space_left_action  /etc/audit/auditd.conf
#space_left_action = email
#
#If the value of the “space_left_action” keyword is not set to email, this is a finding.'

- debug: msg="rhel_07_030351 not implemented"

