---
# STIG: RHEL-07-040180 - The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) authentication communications.
# description: Without cryptographic integrity protections, information can be altered by unauthorized users without detection.  Cryptographic mechanisms used for protecting the integrity of information include, for example, signed hash functions using asymmetric cryptography enabling distribution of the public key to verify the hash information while maintaining the confidentiality of the secret key used to generate the hash.
# severity: 'medium'
# checkid: 'C-RHEL-07-040180_chk'
# fixid: 'F-RHEL-07-040180_fix'
# version: 'RHEL-07-040180'
# ruleid: 'RHEL-07-040180_rule'
# fixtext: 'Configure the operating system to implement cryptography to protect the integrity of LDAP authentication sessions.
#
#Set the USELDAPAUTH=yes in /etc/sysconfig/authconfig.
#
#Set ssl start_tls in /etc/pam_ldap.conf.'
# checktext: 'Verify the operating system implements cryptography to protect the integrity of remote LDAP authentication sessions.
#
#To determine if LDAP is being used for authentication, use the following command:
#
## grep -i useldapauth /etc/sysconfig/authconfig
#USELDAPAUTH=yes
#
#If USELDAPAUTH=yes, then LDAP is being used. To see if LDAP is configured to use TLS, use the following command:
#
## grep -i ssl /etc/pam_ldap.conf
#ssl start_tls
#
#If the “ssl” option is not “start_tls”, this is a finding.'

- debug: msg="rhel_07_040180 not implemented"

