---
# STIG: RHEL-07-010160 - When passwords are changed the number of repeating characters of the same character class must not be more than four characters.
# description: Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks.  Password complexity is one factor of several that determines how long it takes to crack a password. The more complex the password, the greater the number of possible combinations that need to be tested before the password is compromised.
# severity: 'medium'
# checkid: 'C-RHEL-07-010160_chk'
# fixid: 'F-RHEL-07-010160_fix'
# version: 'RHEL-07-010160'
# ruleid: 'RHEL-07-010160_rule'
# fixtext: 'Configure the operating system to require the change of the number of repeating characters of the same character class when passwords are changed by setting the “maxclassrepeat” option.
#
#Add the following line to /etc/security/pwquality.conf conf (or modify the line to have the required value):
#
#maxclassrepeat = 4'
# checktext: 'The "maxclassrepeat" option sets the maximum number of allowed same consecutive characters in the same class in the new password.
#
#Check for the value of the maxclassrepeat option in /etc/security/pwquality.conf with the following command:
#
## grep maxclassrepeat /etc/security/pwquality.conf 
#maxclassrepeat = 4
#
#If the value of “maxclassrepeat” is set to more than 4, this is a finding.'

- debug: msg="rhel_07_010160 not implemented"

