---
# STIG: RHEL-07-020650 - All local interactive user home directories must have mode 0750 or less permissive.
# description: Excessive permissions on local interactive user home directories may allow unauthorized access to user files by other users.
# severity: 'medium'
# checkid: 'C-RHEL-07-020650_chk'
# fixid: 'F-RHEL-07-020650_fix'
# version: 'RHEL-07-020650'
# ruleid: 'RHEL-07-020650_rule'
# fixtext: 'Change the mode of interactive user’s home directories to “0750”. To change the mode of a local interactive user’s home directory, use the following command:
#
#Note: The example will be for the user “smithj”.
#
## chmod 0750 /home/smithj'
# checktext: 'Verify the assigned home directory of all local interactive users has a mode of “0750” or less permissive.
#
#Check the home directory assignment for all non-privileged users on the system with the following command:
#
## cut -d: -f 1,3 /etc/passwd | egrep ":[1-4][0-9]{2}$|:[0-9]{1,2}$"
#smithj /home/smithj
#
#Note: This may miss interactive users that have been assigned a privileged User Identifier (UID). Evidence of interactive use may be obtained from a number of log files containing system logon information.
#
#Check the mode on all local interactive users’ home directories with the following command:
#
## ls -al <users home directory>
#drwxr-x---  1 smithj users        860 Nov 28 06:43 smithj
#
#If home directories referenced in “/etc/passwd” do not have a mode of “0750” or less permissive, this is a finding.'

- debug: msg="rhel_07_020650 not implemented"

