---
# STIG: RHEL-07-010270 - The SSH daemon must not allow authentication using an empty password.
# description: Configuring this setting for the SSH daemon provides additional assurance that remote logon via SSH will require a password, even in the event of misconfiguration elsewhere.
# severity: 'high'
# checkid: 'C-RHEL-07-010270_chk'
# fixid: 'F-RHEL-07-010270_fix'
# version: 'RHEL-07-010270'
# ruleid: 'RHEL-07-010270_rule'
# fixtext: 'To explicitly disallow remote logon from accounts with empty passwords, add or correct the following line in "/etc/ssh/sshd_config":
#
#PermitEmptyPasswords no
#
#Any accounts with empty passwords should be disabled immediately, and PAM configuration should prevent users from being able to assign themselves empty passwords.'
# checktext: 'To determine how the SSH daemon\'s "PermitEmptyPasswords" option is set, run the following command:
#
## grep -i PermitEmptyPasswords /etc/ssh/sshd_config
#
#If no line, a commented line, or a line indicating the value "no" is returned, the required value is set.
#
#If the required value is not set, this is a finding.'

- debug: msg="rhel_07_010270 not implemented"

