---
# STIG: RHEL-07-010072 - The operating system must have the screen package installed.
# description: A session time-out lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not log out because of the temporary nature of the absence. Rather than relying on the user to manually lock their operating system session prior to vacating the vicinity, operating systems need to be able to identify when a user\'s session has idled and take action to initiate the session lock.  The screen package allows for a session lock to be implemented and configured.
# severity: 'medium'
# checkid: 'C-RHEL-07-010072_chk'
# fixid: 'F-RHEL-07-010072_fix'
# version: 'RHEL-07-010072'
# ruleid: 'RHEL-07-010072_rule'
# fixtext: 'Install the screen package to allow the initiation a session lock after a 15-minute period of inactivity for graphical users interfaces.
#
#Install the screen program (if it is not on the system) with the following command:
#
## yum install screen
#
#The console can now be locked with the following key combination: 
#
#ctrl+a x'
# checktext: 'Verify the operating system has the screen package installed.
#
#Check to see if the screen package is installed with the following command:
#
## yum list installed | grep screen
#screen-4.3.1-3-x86_64.rpm
#
#If is not installed, this is a finding.'

- debug: msg="rhel_07_010072 not implemented"

