---
# STIG: RHEL-07-040540 - Remote X connections for interactive users must be encrypted.
# description: Open X displays allow an attacker to capture keystrokes and execute commands remotely.
# severity: 'high'
# checkid: 'C-RHEL-07-040540_chk'
# fixid: 'F-RHEL-07-040540_fix'
# version: 'RHEL-07-040540'
# ruleid: 'RHEL-07-040540_rule'
# fixtext: 'Configure SSH to encrypt connections for interactive users.
#
#Edit the /etc/ssh/sshd_config file to uncomment or add the line for the X11Forwarding keyword and set its value to “yes” (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor):
#
#X11Fowarding yes'
# checktext: 'Verify remote X connections for interactive users are encrypted.
#
#Check that remote X connections are encrypted with the following command:
#
## grep -i x11forwarding /etc/ssh/sshd_config
#X11Fowarding yes
#
#If the X11Forwarding keyword is set to "no", is missing, or is commented out, this is a finding.'

- debug: msg="rhel_07_040540 not implemented"

