---
# STIG: RHEL-07-010090 - When passwords are changed or new passwords are established, the new password must contain at least one upper-case character.
# description: Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks.  Password complexity is one factor of several that determines how long it takes to crack a password. The more complex the password, the greater the number of possible combinations that need to be tested before the password is compromised.
# severity: 'medium'
# checkid: 'C-RHEL-07-010090_chk'
# fixid: 'F-RHEL-07-010090_fix'
# version: 'RHEL-07-010090'
# ruleid: 'RHEL-07-010090_rule'
# fixtext: 'Configure the operating system to enforce password complexity by requiring that at least one upper-case character be used by setting the “ucredit” option.
#
#Add the following line to /etc/security/pwquality.conf (or modify the line to have the required value):
#
#ucredit = -1'
# checktext: 'Note: The value to require a number of upper-case characters to be set is expressed as a negative number in /etc/security/pwquality.conf.
#
#Check the value for "ucredit" in /etc/security/pwquality.conf with the following command:
#
## grep ucredit /etc/security/pwquality.conf 
#ucredit = -1
#
#If the value of "ucredit" is not set to a negative value, this is a finding.'

- debug: msg="rhel_07_010090 not implemented"

