---
# STIG: RHEL-07-030750 - All uses of the rename command must be audited.
# description: If the system is not configured to audit certain activities and write them to an audit log, it is more difficult to detect and track system compromises and damages incurred during a system compromise.  Satisfies: SRG-OS-000466-GPOS-00210, SRG-OS-000467-GPOS-00210, SRG-OS-000468-GPOS-00212, SRG-OS-000392-GPOS-00172
# severity: 'medium'
# checkid: 'C-RHEL-07-030750_chk'
# fixid: 'F-RHEL-07-030750_fix'
# version: 'RHEL-07-030750'
# ruleid: 'RHEL-07-030750_rule'
# fixtext: 'Configure the operating system to generate audit records when successful/unsuccessful attempts to use the rename command occur.
#
#Add the following rules to “/etc/audit/rules.d/audit.rules” (removing those that do not match the CPU architecture):
#
#-a always,exit -F arch=b32 -S rename -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k delete
#-a always,exit -F arch=b64 -S rename -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k delete
#
#The audit daemon must be restarted for the changes to take effect.'
# checktext: 'Verify the operating system generates audit records when successful/unsuccessful attempts to use the rename command occur.
#
#Check the file system rules in /etc/audit/rules.d/audit.rules with the following commands:
#
#Note: The output lines of the command are duplicated to cover both 32-bit and 64-bit architectures. Only the lines appropriate for the system architecture must be present.
#
## grep -i rename /etc/audit/rules.d/audit.rules
#-a always,exit -F arch=b32 -S rename -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k delete
#-a always,exit -F arch=b64 -S rename -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k delete
#
#If the command does not return any output, this is a finding.'

- debug: msg="rhel_07_030750 not implemented"

