---
# STIG: RHEL-07-040810 - The system must use a local firewall.
# description: A firewall provides the ability to enhance system security posture by restricting services to known good IP addresses and address ranges. This prevents connections from unknown hosts and protocols.
# severity: 'medium'
# checkid: 'C-RHEL-07-040810_chk'
# fixid: 'F-RHEL-07-040810_fix'
# version: 'RHEL-07-040810'
# ruleid: 'RHEL-07-040810_rule'
# fixtext: 'Install “firewalld” on the system if it is not already installed with the following command:
#
## yum install firewalld firewall-config
#
#Enable firewalld with the following command:
#
##systemctl enable firewalld'
# checktext: 'Verify that a firewall is in use on the system.
#
#Check to see if “firewalld” is installed with the following command:
#
## yum list installed | grep firewalld
#
#If “firewalld” is not installed, ask the System Administrator if they are performing another method of access control (such as iptables) for all network services on the system. 
#
#If there is no access control being performed on all network services, this is a finding.
#
#If “firewalld” is installed, determine whether it is active with the following command:
#
## systemctl status firewalld
#firewalld.service - firewalld - dynamic firewall daemon
#   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled)
#   Active: active (running) since Sun 2014-04-20 14:06:46 BST; 30s ago
#
#If “firewalld” is not active, this is a finding.'

- debug: msg="rhel_07_040810 not implemented"

