---
# STIG: RHEL-07-010490 - Unnecessary default system accounts must be removed.
# description: Default system accounts created at install time but never used by the system may inadvertently be configured for interactive logon. Vendor accounts and software may contain accounts that provide unauthorized access to the system. All accounts that are not used to support the system and application operation must be removed from the system.
# severity: 'low'
# checkid: 'C-RHEL-07-010490_chk'
# fixid: 'F-RHEL-07-010490_fix'
# version: 'RHEL-07-010490'
# ruleid: 'RHEL-07-010490_rule'
# fixtext: 'Remove unnecessary default accounts from the system by using the account management tool or manually editing the “/etc/password” and “/etc/shadow” files.'
# checktext: 'Verify unnecessary default system accounts have been removed.
#
#Check the accounts that are on the system with the following command:
#
## more /etc/passwd
#root:x:0:0:root:/root:/bin/bash
#bin:x:1:1:bin:/bin:/sbin/nologin
#daemon:x:2:2:daemon:/sbin:/sbin/nologin
#adm:x:3:4:adm:/var/adm:/sbin/nologin
#lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
#sync:x:5:0:sync:/sbin:/bin/sync
#
#If unnecessary default accounts such as games or ftp exist in the “/etc/passwd” file, this is a finding.'

- debug: msg="rhel_07_010490 not implemented"

