---
# STIG: RHEL-07-010170 - The PAM system service must be configured to store only encrypted representations of passwords.
# description: Passwords need to be protected at all times, and encryption is the standard method for protecting passwords. If passwords are not encrypted, they can be plainly read (i.e., clear text) and easily compromised. Passwords encrypted with a weak algorithm are no more protected than if they are kept in plain text.
# severity: 'medium'
# checkid: 'C-RHEL-07-010170_chk'
# fixid: 'F-RHEL-07-010170_fix'
# version: 'RHEL-07-010170'
# ruleid: 'RHEL-07-010170_rule'
# fixtext: 'Configure the operating system to store only SHA512 encrypted representations of passwords.
#
#Add the following line in /etc/pam.d/system-auth:
#
#password sufficient pam_unix.so sha512'
# checktext: 'Verify the PAM system service is configured to store only encrypted representations of passwords. The strength of encryption that must be used to hash passwords for all accounts is SHA512.
#
#Check that the system is configured to create SHA512 hashed passwords with the following command:
#
## grep password /etc/pam.d/system-auth
#password sufficient pam_unix.so sha512
#
#If the /etc/pam.d/system-auth configuration files allow for password hashes other than SHA512 to be used, this is a finding.'

- debug: msg="rhel_07_010170 not implemented"

