---
# STIG: RHEL-07-040210 - The operating system must, for networked systems, synchronize clocks with a server that is synchronized to one of the redundant United States Naval Observatory (USNO) time servers, a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS).
# description: Inaccurate time stamps make it more difficult to correlate events and can lead to an inaccurate analysis. Determining the correct time a particular event occurred on a system is critical when conducting forensic analysis and investigating system events. Sources outside the configured acceptable allowance (drift) may be inaccurate.  Synchronizing internal information system clocks provides uniformity of time stamps for information systems with multiple system clocks and systems connected over a network.  Organizations should consider endpoints that may not have regular access to the authoritative time server (e.g., mobile, teleworking, and tactical endpoints).  Satisfies: SRG-OS-000355-GPOS-00143, SRG-OS-000355-GPOS-00144
# severity: 'medium'
# checkid: 'C-RHEL-07-040210_chk'
# fixid: 'F-RHEL-07-040210_fix'
# version: 'RHEL-07-040210'
# ruleid: 'RHEL-07-040210_rule'
# fixtext: 'Edit the "/etc/ntp.conf" file and add or update an entry to define "maxpoll" to "10" as follows:
#
#maxpoll 10
#
#If NTP was running and "maxpoll" was updated, the ntp service must be restarted:
#
## systemctl restart ntpd
#
#If NTP was not running, it must be started:
#
## systemctl start ntpd'
# checktext: 'Check to see if ntp is running in continuous mode.
#
## ps -ef | grep ntp
#
#If NTP is not running, this is a finding.
#
#If the process is found, then check the ntp.conf file for the “maxpoll” option setting:
#
## grep maxpoll /etc/ntp.conf
#maxpoll 10
#
#If the file does not exist, this is a finding.
#
#If the option is set to “17” or is not set, this is a finding.'

- debug: msg="rhel_07_040210 not implemented"

