---
# STIG: RHEL-07-010060 - The operating system must enable a user session lock until that user re-establishes access using established identification and authentication procedures.
# description: A session lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not want to log out because of the temporary nature of the absence.  The session lock is implemented at the point where session activity can be determined.  Regardless of where the session lock is determined and implemented, once invoked, the session lock must remain in place until the user reauthenticates. No other activity aside from reauthentication must unlock the system.  Satisfies: SRG-OS-000028-GPOS-00009, SRG-OS-000030-GPOS-00011
# severity: 'medium'
# checkid: 'C-RHEL-07-010060_chk'
# fixid: 'F-RHEL-07-010060_fix'
# version: 'RHEL-07-010060'
# ruleid: 'RHEL-07-010060_rule'
# fixtext: 'Configure the operating system to enable a user\'s session lock until that user re-establishes access using established identification and authentication procedures.
#
#Create a database to contain the system-wide screensaver settings (if it does not already exist) with the following command:
#
## touch /etc/dconf/db/local.d/00-screensaver
#
#Add the setting to enable screensaver locking to the file:
#
#[org/gnome/desktop/screensaver]
#lock-enabled=true
#
#After the setting has been set, run dconf update.'
# checktext: 'Verify the operating system enables a user\'s session lock until that user re-establishes access using established identification and authentication procedures. The screen program must be installed to lock sessions on the console.
#
#Note: If the system does not have GNOME installed, this requirement is Not Applicable.
#
#Check to see if the screen lock is enabled with the following command:
#
## grep -i lock-enabled /etc/dconf/db/local.d/00-screensaver
#lock-enabled=true
#
#If the "lock-enabled" setting is missing or is not set to true, this is a finding.'

- debug: msg="rhel_07_010060 not implemented"

