---
# STIG: RHEL-07-021160 - Cron logging must be implemented.
# description: Cron logging can be used to trace the successful or unsuccessful execution of cron jobs. It can also be used to spot intrusions into the use of the cron facility by unauthorized and malicious users.
# severity: 'medium'
# checkid: 'C-RHEL-07-021160_chk'
# fixid: 'F-RHEL-07-021160_fix'
# version: 'RHEL-07-021160'
# ruleid: 'RHEL-07-021160_rule'
# fixtext: 'Configure rsyslog to log all cron messages by adding or updating the following line to /etc/rsyslog.conf:
#
#cron.* /var/log/cron.log
#
#Note: The line must be added before the following entry if it exists in /etc/rsyslog.conf:
#*.* ~ # discards everything'
# checktext: 'Verify that rsyslog is configured to log cron events.
#
#Check the configuration of /etc/rsyslog.conf for the cron facility with the following command:
#
#Note: If another logging package is used, substitute the utility configuration file for /etc/rsyslog.conf. 
#
## grep cron /etc/rsyslog.conf
#cron.* /var/log/cron.log
#
#If the command does not return a response, check for cron logging all facilities by inspecting the /etc/rsyslog.conf file:
#
## more /etc/rsyslog.conf
#
#Look for the following entry:
#
#*.* /var/log/messages
#
#If rsyslog is not logging messages for the cron facility or all facilities, this is a finding.  
#
#If the entry is in the “/etc/rsyslog.conf” file but is after the entry: *.*\', this is a finding.'

- debug: msg="rhel_07_021160 not implemented"

