---
# STIG: RHEL-07-010100 - When passwords are changed or new passwords are established, the new password must contain at least one lower-case character.
# description: Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks.  Password complexity is one factor of several that determines how long it takes to crack a password. The more complex the password, the greater the number of possible combinations that need to be tested before the password is compromised.
# severity: 'medium'
# checkid: 'C-RHEL-07-010100_chk'
# fixid: 'F-RHEL-07-010100_fix'
# version: 'RHEL-07-010100'
# ruleid: 'RHEL-07-010100_rule'
# fixtext: 'Configure the operating system to enforce password complexity by requiring that at least one lower-case character be used by setting the “lcredit” option.
#
#Add the following line to /etc/security/pwquality.conf (or modify the line to have the required value):
#
#lcredit = -1'
# checktext: 'Note: The value to require a number of lower-case characters to be set is expressed as a negative number in /etc/security/pwquality.conf.
#
#Check the value for "lcredit" in /etc/security/pwquality.conf with the following command:
#
## grep lcredit /etc/security/pwquality.conf 
#lcredit = -1 
#
#If the value of "lcredit" is not set to a negative value, this is a finding.'

- debug: msg="rhel_07_010100 not implemented"

