---
# STIG: RHEL-07-040182 - The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications.
# description: Without cryptographic integrity protections, information can be altered by unauthorized users without detection.  Cryptographic mechanisms used for protecting the integrity of information include, for example, signed hash functions using asymmetric cryptography enabling distribution of the public key to verify the hash information while maintaining the confidentiality of the secret key used to generate the hash.
# severity: 'medium'
# checkid: 'C-RHEL-07-040182_chk'
# fixid: 'F-RHEL-07-040182_fix'
# version: 'RHEL-07-040182'
# ruleid: 'RHEL-07-040182_rule'
# fixtext: 'Configure the operating system to implement cryptography to protect the integrity of LDAP remote access sessions.
#
#Set the tls_cacertfile option in /etc/pam_ldap.conf to point to the path for the X.509 certificates used for peer authentication.'
# checktext: 'Verify the operating system implements cryptography to protect the integrity of remote ldap access sessions.
#
#To determine if LDAP is being used for authentication, use the following command:
#
## grep -i useldapauth /etc/sysconfig/authconfig
#USELDAPAUTH=yes
#
#If USELDAPAUTH=yes, then LDAP is being used.
#
#Check that the path to the X.509 certificate for peer authentication with the following command:
#
## grep -i cacertfile /etc/pam_ldap.conf
#tls_cacertfile /etc/openldap/ldap-cacert.pem
#
#Verify the “tls_cacertfile” option points to a file that contains the trusted CA certificate.
#
#If this file does not exist, or the option is commented out or missing, this is a finding.'

- debug: msg="rhel_07_040182 not implemented"

