---
# STIG: RHEL-07-020370 - All files and directories must have a valid group owner.
# description: Files without a valid group owner may be unintentionally inherited if a group is assigned the same Group Identifier (GID) as the GID of the files without a valid group owner.
# severity: 'medium'
# checkid: 'C-RHEL-07-020370_chk'
# fixid: 'F-RHEL-07-020370_fix'
# version: 'RHEL-07-020370'
# ruleid: 'RHEL-07-020370_rule'
# fixtext: 'Either remove all files and directories from the system that do not have a valid group, or assign a valid group to all files and directories on the system with the chgrp command:
#
## chgrp <group> <file>'
# checktext: 'Verify all files and directories on the system have a valid group.
#
#Check the owner of all files and directories with the following command:
#
## find / -fstype local -xdev -nogroup
#
#If any files on the system do not have an assigned group, this is a finding.'

- debug: msg="rhel_07_020370 not implemented"

