---
# STIG: RHEL-07-030770 - The system must send rsyslog output to a log aggregation server.
# description: Sending rsyslog output to another system ensures that the logs cannot be removed or modified in the event that the system is compromised or has a hardware failure.
# severity: 'medium'
# checkid: 'C-RHEL-07-030770_chk'
# fixid: 'F-RHEL-07-030770_fix'
# version: 'RHEL-07-030770'
# ruleid: 'RHEL-07-030770_rule'
# fixtext: 'Modify the “/etc/rsyslog.conf” file to contain a configuration line to send all “rsyslog” output to a log aggregation system:
#
#*.* @@<log aggregation system name>'
# checktext: 'Verify “rsyslog” is configured to send all messages to a log aggregation server.
#
#Check the configuration of “rsyslog” with the following command:
#
## grep @ /etc/rsyslog.conf
#*.* @@logagg.site.mil
#
#If there are no lines in the “/etc/rsyslog.conf” file that contain the “@” or “@@” symbol(s), and the lines with the correct symbol(s) to send output to another system do not cover all “rsyslog” output, this is a finding.'

- debug: msg="rhel_07_030770 not implemented"

