---
# STIG: RHEL-07-020860 - All local initialization files must have mode 0740 or less permissive.
# description: Local initialization files are used to configure the user\'s shell environment upon logon. Malicious modification of these files could compromise accounts upon logon.
# severity: 'medium'
# checkid: 'C-RHEL-07-020860_chk'
# fixid: 'F-RHEL-07-020860_fix'
# version: 'RHEL-07-020860'
# ruleid: 'RHEL-07-020860_rule'
# fixtext: 'Set the mode of the local initialization files to “0740” with the following command:
#
#Note: The example will be for the smithj user, who has a home directory of “/home/smithj”.
#
## chmod 0740 /home/smithj/.*'
# checktext: 'Verify that all local initialization files have a mode of “0740” or less permissive.
#
#Check the mode on all local initialization files with the following command:
#
#Note: The example will be for the smithj user, who has a home directory of “/home/smithj”.
#
## ls -al /home/smithj/.* | more
#-rwxr-xr-x  1 smithj users        896 Mar 10  2011 .profile
#-rwxr-xr-x  1 smithj users        497 Jan  6  2007 .login
#-rwxr-xr-x  1 smithj users        886 Jan  6  2007 .something
#
#If any local initialization files have a mode more permissive than “0740”, this is a finding.'

- debug: msg="rhel_07_020860 not implemented"

