---
# STIG: RHEL-07-020220 - The x86 Ctrl-Alt-Delete key sequence must be disabled.
# description: A locally logged-on user who presses Ctrl-Alt-Delete, when at the console, can reboot the system. If accidentally pressed, as could happen in the case of a mixed OS environment, this can create the risk of short-term loss of availability of systems due to unintentional reboot. In the GNOME graphical environment, risk of unintentional reboot from the Ctrl-Alt-Delete sequence is reduced because the user will be prompted before any action is taken.
# severity: 'high'
# checkid: 'C-RHEL-07-020220_chk'
# fixid: 'F-RHEL-07-020220_fix'
# version: 'RHEL-07-020220'
# ruleid: 'RHEL-07-020220_rule'
# fixtext: 'Configure the system to disable the Ctrl-Alt_Delete sequence for the command line with the following command:
#
## systemctl mask ctrl-alt-del.target
#
#If Gnome is active on the system, create a database to contain the system-wide setting (if it does not already exist) with the following command: 
#
## cat /etc/dconf/db/local.d/00-disable-CAD 
#
#Add the setting to disable the Ctrl-Alt_Delete sequence for Gnome:
#
#[org/gnome/settings-daemon/plugins/media-keys]
#logout=’’'
# checktext: 'Verify the operating system is not configured to reboot the system when Ctrl-Alt-Delete is pressed.
#
#Check that the ctrl-alt-del.service is not active with the following command:
#
## systemctl status ctrl-alt-del.service
#reboot.target - Reboot
#   Loaded: loaded (/usr/lib/systemd/system/reboot.target; disabled)
#   Active: inactive (dead)
#     Docs: man:systemd.special(7)
#
#If the ctrl-alt-del.service is active , this is a finding.'

- debug: msg="rhel_07_020220 not implemented"

