---
# STIG: RHEL-07-010190 - User and group account administration utilities must be configured to store only encrypted representations of passwords.
# description: Passwords need to be protected at all times, and encryption is the standard method for protecting passwords. If passwords are not encrypted, they can be plainly read (i.e., clear text) and easily compromised. Passwords encrypted with a weak algorithm are no more protected than if they are kept in plain text.
# severity: 'medium'
# checkid: 'C-RHEL-07-010190_chk'
# fixid: 'F-RHEL-07-010190_fix'
# version: 'RHEL-07-010190'
# ruleid: 'RHEL-07-010190_rule'
# fixtext: 'Configure the operating system to store only SHA512 encrypted representations of passwords.
#
#Add or update the following line in /etc/libuser.conf in the [defaults] section: 
#
#crypt_style = sha512'
# checktext: 'Verify the user and group account administration utilities are configured to store only encrypted representations of passwords. The strength of encryption that must be used to hash passwords for all accounts is SHA512.
#
#Check that the system is configured to create SHA512 hashed passwords with the following command:
#
## cat /etc/libuser.conf | grep -i sha512
#[defaults]
#
#crypt_style = sha512
#
#If the "crypt_style" variable is not set to "sha512", is not in the defaults section, or does not exist, this is a finding.'

- debug: msg="rhel_07_010190 not implemented"

