---
# STIG: RHEL-07-040730 - The system must not be performing packet forwarding unless the system is a router.
# description: Routing protocol daemons are typically used on routers to exchange network topology information with other routers. If this software is used when not required, system network information may be unnecessarily transmitted across the network.
# severity: 'medium'
# checkid: 'C-RHEL-07-040730_chk'
# fixid: 'F-RHEL-07-040730_fix'
# version: 'RHEL-07-040730'
# ruleid: 'RHEL-07-040730_rule'
# fixtext: 'Set the system to the required kernel parameter by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):
#
#net.ipv4.ip_forward = 0'
# checktext: 'Verify the system is not performing packet forwarding, unless the system is a router.
#
#Check to see if IP forwarding is enabled using the following command:
#
## /sbin/sysctl -a | grep  net.ipv4.ip_forward
#net.ipv4.ip_forward=0
#
#If IP forwarding value is “1” and the system is hosting any application, database, or web servers, this is a finding.'

- debug: msg="rhel_07_040730 not implemented"

