---
# STIG: RHEL-07-040160 - All network connections associated with a communication session must be terminated at the end of the session or after 10 minutes of inactivity from the user at a command prompt, except to fulfill documented and validated mission requirements.
# description: Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session will also free up resources committed by the managed network element.   Terminating network connections associated with communications sessions includes, for example, de-allocating associated TCP/IP address/port pairs at the operating system level and de-allocating networking assignments at the application level if multiple application sessions are using a single operating system-level network connection. This does not mean that the operating system terminates all sessions or network access; it only ends the inactive session and releases the resources associated with that session.
# severity: 'medium'
# checkid: 'C-RHEL-07-040160_chk'
# fixid: 'F-RHEL-07-040160_fix'
# version: 'RHEL-07-040160'
# ruleid: 'RHEL-07-040160_rule'
# fixtext: 'Configure the operating system to terminate all network connections associated with a communications session at the end of the session or after a period of inactivity.
#
#Add the following line to /etc/profile (or modify the line to have the required value):
#
#TMOUT=600'
# checktext: 'Verify the operating system terminates all network connections associated with a communications session at the end of the session or based on inactivity.
#
#Check the value of the system inactivity timeout with the following command:
#
## grep -i tmout /etc/profile 
#TMOUT=600
#
#If “TMOUT” is not set to 600 or less in /etc/profile, this is a finding.'

- debug: msg="rhel_07_040160 not implemented"

