---
# STIG: RHEL-07-040520 - If the Trivial File Transfer Protocol (TFTP) server is required, the TFTP daemon must be configured to operate in secure mode.
# description: Restricting TFTP to a specific directory prevents remote users from copying, transferring, or overwriting system files.
# severity: 'medium'
# checkid: 'C-RHEL-07-040520_chk'
# fixid: 'F-RHEL-07-040520_fix'
# version: 'RHEL-07-040520'
# ruleid: 'RHEL-07-040520_rule'
# fixtext: 'Configure the TFTP daemon to operate in secure mode by adding the following line to /etc/xinetd.d/tftp (or modify the line to have the required value):
#
#server_args = -s /var/lib/tftpboot'
# checktext: 'Verify the TFTP daemon is configured to operate in secure mode.
#
#Check to see if a TFTP server has been installed with the following commands:
#
## yum list installed | grep tftp
#tftp-0.49-9.el7.x86_64.rpm
#
#If a TFTP server is not installed, this is Not Applicable.
#
#If a TFTP server is installed, check for the server arguments with the following command: 
#
## grep server_arge /etc/xinetd.d/tftp
#server_args = -s /var/lib/tftpboot
#
#If the “server_args” line does not have a -s option and the directory /var/lib/tftpboot, this is a finding.'

- debug: msg="rhel_07_040520 not implemented"

