---
# STIG: RHEL-07-020230 - The operating system must define default permissions for all authenticated users in such a way that the user can only read and modify their own files.
# description: Setting the most restrictive default permissions ensures that when new accounts are created, they do not have unnecessary access.
# severity: 'medium'
# checkid: 'C-RHEL-07-020230_chk'
# fixid: 'F-RHEL-07-020230_fix'
# version: 'RHEL-07-020230'
# ruleid: 'RHEL-07-020230_rule'
# fixtext: 'Configure the operating system to define default permissions for all authenticated users in such a way that the user can only read and modify their own files.
#
#Add or edit the line for the “UMASK” parameter in “/etc/login.defs” file to “077”:
#
#UMASK  077'
# checktext: 'Verify the operating system defines default permissions for all authenticated users in such a way that the user can only read and modify their own files.
#
#Check for the value of the “UMASK” parameter in “/etc/login.defs” file with the following command:
#
#Note: If the value of the “UMASK” parameter is set to “000” in “/etc/login.defs” file, the Severity is raised to a CAT I.
#
## grep -i umask /etc/login.defs
#UMASK  077
#
#If the value for the “UMASK” parameter is not “077”, or the “UMASK” parameter is missing or is commented out, this is a finding.'

- debug: msg="rhel_07_020230 not implemented"

