---
# STIG: RHEL-07-040680 - The SSH daemon must perform strict mode checking of home directory configuration files.
# description: If other users have access to modify user-specific SSH configuration files, they may be able to log on to the system as another user.
# severity: 'medium'
# checkid: 'C-RHEL-07-040680_chk'
# fixid: 'F-RHEL-07-040680_fix'
# version: 'RHEL-07-040680'
# ruleid: 'RHEL-07-040680_rule'
# fixtext: 'Uncomment the “StrictModes” keyword in /etc/ssh/sshd_config (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor) and set the value to "yes":
#
#StrictModes yes'
# checktext: 'Verify the SSH daemon performs strict mode checking of home directory configuration files.
#
#The location of the sshd_config file may vary on the system and can be found using the following command:
#
## find / -name \'sshd*_config\' 
#
#If there is more than one ssh server daemon configuration file on the system, determine which daemons are active on the system with the following command:
#
## ps -ef | grep sshd
#
#The command will return the full path of the ssh daemon. This will indicate which sshd_config file will be checked with the following command:
#
## grep -i strictmodes /etc/ssh/sshd_config
#StrictModes yes
#
#If “StrictModes” is set to "no", is missing, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040680 not implemented"

