---
# STIG: RHEL-07-020360 - All files and directories must have a valid owner.
# description: Unowned files and directories may be unintentionally inherited if a user is assigned the same User Identifier “UID” as the UID of the un-owned files.
# severity: 'medium'
# checkid: 'C-RHEL-07-020360_chk'
# fixid: 'F-RHEL-07-020360_fix'
# version: 'RHEL-07-020360'
# ruleid: 'RHEL-07-020360_rule'
# fixtext: 'Either remove all files and directories from the system that do not have a valid user, or assign a valid user to all unowned files and directories on the system with the chown command:
#
## chown <user> <file>'
# checktext: 'Verify all files and directories on the system have a valid owner.
#
#Check the owner of all files and directories with the following command:
#
## find / -fstype local -xdev -nouser
#
#If any files on the system do not have an assigned owner, this is a finding.'

- debug: msg="rhel_07_020360 not implemented"

