---
# STIG: RHEL-07-030550 - All uses of the ssh-keysign command must be audited.
# description: Reconstruction of harmful events or forensic analysis is not possible if audit records do not contain enough information.  At a minimum, the organization must audit the full-text recording of privileged ssh commands. The organization must maintain audit trails in sufficient detail to reconstruct events to determine the cause and impact of compromise.  Satisfies: SRG-OS-000042-GPOS-00020, SRG-OS-000392-GPOS-00172, SRG-OS-000471-GPOS-00215
# severity: 'medium'
# checkid: 'C-RHEL-07-030550_chk'
# fixid: 'F-RHEL-07-030550_fix'
# version: 'RHEL-07-030550'
# ruleid: 'RHEL-07-030550_rule'
# fixtext: 'Configure the operating system to generate audit records when successful/unsuccessful attempts to use the ssh-keysign command occur. 
#
#Add or update the following rule to /etc/audit/rules.d/audit.rules: 
#
#-a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k privileged-ssh
#
#The audit daemon must be restarted for the changes to take effect.'
# checktext: 'Verify the operating system generates audit records when successful/unsuccessful attempts to use the ssh-keysign command occur. 
#
#Check for the following system call being audited by performing the following command to check the file system rules in /etc/audit/rules.d/audit.rules: 
#
## grep -i /usr/libexec/openssh/ssh-keysign /etc/audit/rules.d/audit.rules
#
#-a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k privileged-ssh
#
#If the command does not return any output, this is a finding.'

- debug: msg="rhel_07_030550 not implemented"

