---
# STIG: RHEL-07-010010 - The file permissions, ownership, and group membership of system files and commands must match the vendor values.
# description: Discretionary access control is weakened if a user or group has access permissions to system files and directories greater than the default.  Satisfies: SRG-OS-000257-GPOS-00098, SRG-OS-000278-GPOS-00108
# severity: 'high'
# checkid: 'C-RHEL-07-010010_chk'
# fixid: 'F-RHEL-07-010010_fix'
# version: 'RHEL-07-010010'
# ruleid: 'RHEL-07-010010_rule'
# fixtext: 'Run the following command to determine which package owns the file:
#
## rpm -qf <filename>
#
#Reset the permissions of files within a package with the following command:
#
##rpm --setperms <packagename>
#
#Reset the user and group ownership of files within a package with the following command:
#
##rpm --setugids <packagename>'
# checktext: 'Verify the file permissions, ownership, and group membership of system files and commands match the vendor values.
#Check the file permissions, ownership, and group membership of system files and commands with the following command:
#
## rpm -Va | grep \'^.M\'
#
#If there is any output from the command, this is a finding.'

- name: check perms of system files
  shell: rpm -Va | grep '^.M' | awk '{ print $2 }'
  register: rhel_07_010010_findings
  changed_when: false
  failed_when: false

- block:

  - debug:
      msg: rhel_07_010010 findings - {{ rhel_07_010010_findings.stdout_lines }}

  - name: find package for finding
    command: "rpm -qf {{ item }}"
    changed_when: false
    register: rhel_07_010010_packages
    with_items: "{{ rhel_07_010010_findings.stdout_lines }}"

  - name: fix permission for rhel_07_010010
    command: "rpm --setperms {{ item.stdout }}"
    with_items: "{{ rhel_07_010010_packages.results }}"

  - name: fix ownership for rhel_07_010010
    command: "rpm --setugids {{ item.stdout }}"
    with_items: "{{ rhel_07_010010_packages.results }}"

  when: rhel_07_010010_findings.stdout_lines|length > 0
