---
# STIG: RHEL-07-040050 - The operating system must map the authenticated identity to the user or group account for PKI-based authentication.
# description: Without mapping the certificate used to authenticate to the user account, the ability to determine the identity of the individual user or group will not be available for forensic analysis.
# severity: 'medium'
# checkid: 'C-RHEL-07-040050_chk'
# fixid: 'F-RHEL-07-040050_fix'
# version: 'RHEL-07-040050'
# ruleid: 'RHEL-07-040050_rule'
# fixtext: 'Configure the operating system to map the authenticated identity to the user or group account for PKI-based authentication by creating the common name map file with the following command:
#
## touch /etc/pam_pkcs11/subject_mapping'
# checktext: 'Verify the operating system maps the authenticated identity to the user or group account for PKI–based authentication by verifying the common name map file exists with the following command:
#
## ls –al /etc/pam_pkcs11/cn_map
#–rw–r––––– 1 root root 1294 Apr 22 17:22 /etc/pam_pkcs11/subject_mapping
#
#If the file does not exist, this is a finding.'

- debug: msg="rhel_07_040050 not implemented"

