---
# STIG: RHEL-07-010210 - Passwords must be restricted to a 24 hours/1 day minimum lifetime.
# description: Enforcing a minimum password lifetime helps to prevent repeated password changes to defeat the password reuse or history enforcement requirement. If users are allowed to immediately and continually change their password, the password could be repeatedly changed in a short period of time to defeat the organization\'s policy regarding password reuse.
# severity: 'medium'
# checkid: 'C-RHEL-07-010210_chk'
# fixid: 'F-RHEL-07-010210_fix'
# version: 'RHEL-07-010210'
# ruleid: 'RHEL-07-010210_rule'
# fixtext: 'Configure non-compliant accounts to enforce a 24 hours/1 day minimum password lifetime:
#
## chage -m 1 [user]'
# checktext: 'Check whether the minimum time period between password changes for each user account is one day or greater.
#
## awk -F: \'$4 < 1 {print $1}\' /etc/shadow
#
#If any results are returned that are not associated with a system account, this is a finding.'

- debug: msg="rhel_07_010210 not implemented"

