---
# STIG: RHEL-07-010020 - The cryptographic hash of system files and commands must match vendor values.
# description: Without cryptographic integrity protections, system command and files can be altered by unauthorized users without detection.  Cryptographic mechanisms used for protecting the integrity of information include, for example, signed hash functions using asymmetric cryptography enabling distribution of the public key to verify the hash information while maintaining the confidentiality of the secret key used to generate the hash.
# severity: 'high'
# checkid: 'C-RHEL-07-010020_chk'
# fixid: 'F-RHEL-07-010020_fix'
# version: 'RHEL-07-010020'
# ruleid: 'RHEL-07-010020_rule'
# fixtext: 'Run the following command to determine which package owns the file:
#
## rpm -qf <filename>
#
#The package can be reinstalled from a yum repository using the command:
#
## sudo yum reinstall <packagename>
#
#Alternatively, the package can be reinstalled from trusted media using the command:
#
## sudo rpm -Uvh <packagename>'
# checktext: 'Verify the cryptographic hash of system files and commands match the vendor values.
#
#Check the cryptographic hash of system files and commands with the following command:
#
#Note: System configuration files (indicated by a "c" in the second column) are expected to change over time. Unusual modifications should be investigated through the system audit log.
#
## rpm -Va | grep \'^..5\'
#
#If there is any output from the command for system binaries, this is a finding.'

- name: check perms of system files
  shell: rpm -Va | grep '^..5' | awk '{ print $2 }' | grep -v '^c'
  register: rhel_07_010020_findings
  changed_when: false
  failed_when: false

- block:

  - debug:
      msg: rhel_07_010020 findings - {{ rhel_07_010020_findings.stdout_lines }}

  - name: find package for finding
    command: "rpm -qf {{ item }}"
    changed_when: false
    register: rhel_07_010020_packages
    with_items: "{{ rhel_07_010020_findings.stdout_lines }}"

  - name: fix packages for rhel_07_010020 findings
    command: "yum reinstall -y {{ item.stdout }}"
    with_items: "{{ rhel_07_010020_packages.results }}"

  when: rhel_07_010020_findings.stdout_lines|length > 0

