---
# STIG: RHEL-07-040301 - The system must display the date and time of the last successful account logon upon an SSH logon.
# description: Providing users with feedback on when account accesses via SSH last occurred facilitates user recognition and reporting of unauthorized account use.
# severity: 'medium'
# checkid: 'C-RHEL-07-040301_chk'
# fixid: 'F-RHEL-07-040301_fix'
# version: 'RHEL-07-040301'
# ruleid: 'RHEL-07-040301_rule'
# fixtext: 'Configure SSH to provide users with feedback on when account accesses last occurred by setting the required configuration options in “/etc/pam.d/sshd” or in the “sshd_config” file used by the system (/etc/ssh/sshd_config will be used in the example) (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor).
#
#Add the following line to the top of “/etc/pam.d/sshd”:
#
#session     required      pam_lastlog.so showfailed
#
#Or modify the PrintLastLog line in “/etc/ssh/sshd_config” to match the following:
#
#PrintLastLog yes'
# checktext: 'Verify SSH provides users with feedback on when account accesses last occurred.
#
#Check that “PrintLastLog” keyword in the sshd daemon configuration file is used and set to “yes” with the following command:
#
## grep -i printlastlog /etc/ssh/sshd_config
#PrintLastLog yes
#
#If the “PrintLastLog” keyword is set to “no”, is missing, or is commented out, this is a finding.'

- debug: msg="rhel_07_040301 not implemented"

