---
# STIG: RHEL-07-010250 - Passwords must be a minimum of 15 characters in length.
# description: The shorter the password, the lower the number of possible combinations that need to be tested before the password is compromised.  Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks. Password length is one factor of several that helps to determine strength and how long it takes to crack a password. Use of more characters in a password helps to exponentially increase the time and/or resources required to compromise the password.
# severity: 'medium'
# checkid: 'C-RHEL-07-010250_chk'
# fixid: 'F-RHEL-07-010250_fix'
# version: 'RHEL-07-010250'
# ruleid: 'RHEL-07-010250_rule'
# fixtext: 'Configure operating system to enforce a minimum 15-character password length.
#
#Add the following line to /etc/security/pwquality.conf conf (or modify the line to have the required value):
#
#minlen = 15'
# checktext: 'Verify the operating system enforces a minimum 15-character password length. The “minlen” option sets the minimum number of characters in a new password.
#
#Check for the value of the “minlen” option in /etc/security/pwquality.conf with the following command:
#
## grep minlen /etc/security/pwquality.conf
#minlen = 15
#
#If the command does not return a “minlen” value of 15 or greater, this is a finding.'

- debug: msg="rhel_07_010250 not implemented"

