---
# STIG: RHEL-07-040300 - The system must display the date and time of the last successful account logon upon logon.
# description: Providing users with feedback on when account accesses last occurred facilitates user recognition and reporting of unauthorized account use.
# severity: 'low'
# checkid: 'C-RHEL-07-040300_chk'
# fixid: 'F-RHEL-07-040300_fix'
# version: 'RHEL-07-040300'
# ruleid: 'RHEL-07-040300_rule'
# fixtext: 'Configure the operating system to provide users with feedback on when account accesses last occurred by setting the required configuration options in “/etc/pam.d/postlogin”. 
#
#Add the following line to the top of “/etc/pam.d/postlogin”:
#
#session     required      pam_lastlog.so showfailed'
# checktext: 'Verify that users are provided with feedback on when account accesses last occurred.
#
#Check that “pam_lastlog” is used and not silent with the following command:
#
## grep pam_lastlog /etc/pam.d/postlogin
#
#session     required      pam_lastlog.so showfailed silent
#
#If “pam_lastlog” is missing from “/etc/pam.d/postlogin” file, or the silent option is present on the line check for the “PrintLastLog” keyword in the sshd daemon configuration file, this is a finding.'

- debug: msg="rhel_07_040300 not implemented"

