---
# STIG: RHEL-07-010420 - The delay between logon prompts following a failed console logon attempt must be at least four seconds.
# description: Configuring the operating system to implement organization-wide security implementation guides and security checklists verifies compliance with federal standards and establishes a common security baseline across DoD that reflects the most restrictive security posture consistent with operational requirements.  Configuration settings are the set of parameters that can be changed in hardware, software, or firmware components of the system that affect the security posture and/or functionality of the system. Security-related parameters are those parameters impacting the security state of the system, including the parameters required to satisfy other security control requirements. Security-related parameters include, for example, registry settings; account, file, and directory permission settings; and settings for functions, ports, protocols, services, and remote connections.
# severity: 'medium'
# checkid: 'C-RHEL-07-010420_chk'
# fixid: 'F-RHEL-07-010420_fix'
# version: 'RHEL-07-010420'
# ruleid: 'RHEL-07-010420_rule'
# fixtext: 'Configure the operating system to enforce a delay of at least four seconds between logon prompts following a failed console logon attempt.
#
#Modify the “/etc/login.defs” file to set the “FAIL_DELAY” parameter to “4” or greater:
#
#FAIL_DELAY 4'
# checktext: 'Verify the operating system enforces a delay of at least four seconds between console logon prompts following a failed logon attempt.
#
#Check the value of the fail_delay parameter in “/etc/login.defs” file with the following command:
#
## grep -i fail_delay /etc/login.defs
#FAIL_DELAY 4
#
#If the value of “FAIL_DELAY” is not set to “4” or greater, this is a finding.'

- debug: msg="rhel_07_010420 not implemented"

