---
# STIG: RHEL-07-020211 - The operating system must enable the SELinux targeted policy.
# description: Without verification of the security functions, security functions may not operate correctly and the failure may go unnoticed. Security function is defined as the hardware, software, and/or firmware of the information system responsible for enforcing the system security policy and supporting the isolation of code and data on which the protection is based. Security functionality includes, but is not limited to, establishing system accounts, configuring access authorizations (i.e., permissions, privileges), setting events to be audited, and setting intrusion detection parameters.  This requirement applies to operating systems performing security function verification/testing and/or systems and environments that require this functionality.
# severity: 'high'
# checkid: 'C-RHEL-07-020211_chk'
# fixid: 'F-RHEL-07-020211_fix'
# version: 'RHEL-07-020211'
# ruleid: 'RHEL-07-020211_rule'
# fixtext: 'Configure the operating system to verify correct operation of all security functions.
#
#Set the “Selinuxtype” to the “targeted” policy by modifying the /etc/selinux/config file to have the following line:
#
#SELINUXTYPE=targeted
#
#A reboot is required for the changes to take effect.'
# checktext: 'Verify the operating system verifies correct operation of all security functions.
#
#Check if SELinux is active and is enforcing the targeted policy with the following command:
#
## sestatus
#SELinux status:                 enabled
#SELinuxfs mount:                /selinux
#Current mode:                   enforcing
#Mode from config file:          enforcing
#Policy version:                 24
#Policy from config file:        targeted
#
#If the “Policy from config file”  not set to “targeted”, this is a finding.'

- debug: msg="rhel_07_020211 not implemented"

