---
# STIG: RHEL-07-020620 - All local interactive users must have a home directory assigned in the /etc/passwd file.
# description: If local interactive users are not assigned a valid home directory, there is no place for the storage and control of files they should own.
# severity: 'medium'
# checkid: 'C-RHEL-07-020620_chk'
# fixid: 'F-RHEL-07-020620_fix'
# version: 'RHEL-07-020620'
# ruleid: 'RHEL-07-020620_rule'
# fixtext: 'Assign home directories to all local interactive users that currently do not have a home directory assigned.'
# checktext: 'Verify local interactive users on the system have a home directory assigned.
#
#Check for missing local interactive user home directories with the following command:
#
## pwck -r
#user \'lp\': directory \'/var/spool/lpd\' does not exist
#user \'news\': directory \'/var/spool/news\' does not exist
#user \'uucp\': directory \'/var/spool/uucp\' does not exist
#user \'smithj\': directory \'/home/smithj\' does not exist
#
#Ask the System Administrator (SA) if any users found without home directories are local interactive users. If the SA is unable to provide a response, check for users with a User Identifier (UID) of 1000 or greater with the following command:
#
## cut -d: -f 1,3 /etc/passwd | egrep ":[1-4][0-9]{2}$|:[0-9]{1,2}$"
#
#If any interactive users do not have a home directory assigned, this is a finding.'

- debug: msg="rhel_07_020620 not implemented"

