---
# STIG: RHEL-07-030630 - All uses of the pam_timestamp_check command must be audited.
# description: Without generating audit records that are specific to the security and mission needs of the organization, it would be difficult to establish, correlate, and investigate the events relating to an incident or identify those responsible for one.
# severity: 'medium'
# checkid: 'C-RHEL-07-030630_chk'
# fixid: 'F-RHEL-07-030630_fix'
# version: 'RHEL-07-030630'
# ruleid: 'RHEL-07-030630_rule'
# fixtext: 'Configure the operating system to generate audit records when successful/unsuccessful attempts to use the pam_timestamp_check command occur. 
#
#Add or update the following rule in /etc/audit/rules.d/audit.rules: 
#
#-a always,exit -F path=/sbin/pam_timestamp_check -F perm=x -F auid>=1000 -F auid!=4294967295 -F auid!=4294967295 -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k privileged-pam
#
#The audit daemon must be restarted for the changes to take effect.'
# checktext: 'Verify the operating system generates audit records when successful/unsuccessful attempts to use the pam_timestamp_check command occur. 
#
#Check the auditing rules in /etc/audit/rules.d/audit.rules with the following command:
#
## grep -i /sbin/pam_timestamp_check /etc/audit/rules.d/audit.rules
#
#-a always,exit -F path=/sbin/pam_timestamp_check -F perm=x -F auid>=1000 -F auid!=4294967295  -F subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 -k privileged-pam  
#
#If the command does not return any output, this is a finding.'

- debug: msg="rhel_07_030630 not implemented"

