---
# STIG: RHEL-07-020300 - All Group Identifiers (GIDs) referenced in the /etc/passwd file must be defined in the /etc/group file.
# description: If a user is assigned the GID of a group not existing on the system, and a group with the GID is subsequently created, the user may have unintended rights to any files associated with the group.
# severity: 'low'
# checkid: 'C-RHEL-07-020300_chk'
# fixid: 'F-RHEL-07-020300_fix'
# version: 'RHEL-07-020300'
# ruleid: 'RHEL-07-020300_rule'
# fixtext: 'Configure the system to define all GIDs found in the “/etc/passwd” file by modifying the “/etc/group” file to add any non-existent group referenced in the “/etc/passwd” file, or change the GIDs referenced in the “/etc/passwd” file to a group that exists in “/etc/group”.'
# checktext: 'Verify all GIDs referenced in the “/etc/passwd” file are defined in the “/etc/group” file.
#
#Check that all referenced GIDs exist with the following command:
#
## pwck -r
#
#If GIDs referenced in “/etc/passwd” file are returned as not defined in “/etc/group” file, this is a finding.'

- debug: msg="rhel_07_020300 not implemented"

