---
# STIG: RHEL-07-021190 - If the cron.allow file exists it must be owned by root.
# description: If the owner of the "cron.allow" file is not set to root, the possibility exists for an unauthorized user to view or to edit sensitive information.
# severity: 'medium'
# checkid: 'C-RHEL-07-021190_chk'
# fixid: 'F-RHEL-07-021190_fix'
# version: 'RHEL-07-021190'
# ruleid: 'RHEL-07-021190_rule'
# fixtext: 'Set the owner on the “/etc/cron.allow” file to root with the following command:
#
## chown root /etc/cron.allow'
# checktext: 'Verify that the "cron.allow" file is owned by root.
#
#Check the owner of the "cron.allow" file with the following command:
#
## l s -al /etc/cron.allow
#-rw------- 1 root root 6 Mar  5  2011 /etc/cron.allow
#
#If the “cron.allow” file exists and has an owner other than root, this is a finding.'

- debug: msg="rhel_07_021190 not implemented"

