---
# STIG: RHEL-07-010230 - Existing passwords must be restricted to a 60-day maximum lifetime.
# description: Any password, no matter how complex, can eventually be cracked. Therefore, passwords need to be changed periodically. If the operating system does not limit the lifetime of passwords and force users to change their passwords, there is the risk that the operating system passwords could be compromised.
# severity: 'medium'
# checkid: 'C-RHEL-07-010230_chk'
# fixid: 'F-RHEL-07-010230_fix'
# version: 'RHEL-07-010230'
# ruleid: 'RHEL-07-010230_rule'
# fixtext: 'Configure non-compliant accounts to enforce a 60-day maximum password lifetime restriction.
#
## chage -M 60 [user]'
# checktext: 'Check whether the maximum time period for existing passwords is restricted to 60 days.
#
## awk -F: \'$5 > 60 {print $1}\' /etc/shadow
#
#If any results are returned that are not associated with a system account, this is a finding.'

- debug: msg="rhel_07_010230 not implemented"

