---
# STIG: RHEL-07-040421 - The system must not send Internet Protocol version 4 (IPv4) Internet Control Message Protocol (ICMP) redirects.
# description: ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular destination. These messages contain information from the system\'s route table, possibly revealing portions of the network topology.
# severity: 'medium'
# checkid: 'C-RHEL-07-040421_chk'
# fixid: 'F-RHEL-07-040421_fix'
# version: 'RHEL-07-040421'
# ruleid: 'RHEL-07-040421_rule'
# fixtext: 'Configure the system to not allow interfaces to perform IPv4 ICMP redirects. 
#
#Set the system to the required kernel parameter by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):
#
#net.ipv4.conf.all.send_redirects=0'
# checktext: 'Verify the system does not send IPv4 ICMP redirect messages.
#
#Check the value of the "all send_redirects" variables with the following command:
#
## /sbin/sysctl -a | grep  net.ipv4.conf.all.send_redirects
#
#net.ipv4.conf.all.send_redirects=0
#
#If the returned line does not have a value of “0”, a line is not returned, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040421 not implemented"

