---
# STIG: RHEL-07-040380 - The system must not respond to Internet Protocol version 4 (IPv4) Internet Control Message Protocol (ICMP) echoes sent to a broadcast address.
# description: Responding to broadcast (ICMP) echoes facilitates network mapping and provides a vector for amplification attacks.
# severity: 'medium'
# checkid: 'C-RHEL-07-040380_chk'
# fixid: 'F-RHEL-07-040380_fix'
# version: 'RHEL-07-040380'
# ruleid: 'RHEL-07-040380_rule'
# fixtext: 'Set the system to the required kernel parameter with the following command:
#
## /sbin/sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1'
# checktext: 'Verify the system does not respond to IPv4 ICMP echoes sent to a broadcast address.
#
#Check the value of the icmp_echo_ignore_broadcasts variable with the following command:
#
## /sbin/sysctl -a | grep  net.ipv4.icmp_echo_ignore_broadcasts
#net.ipv4.icmp_echo_ignore_broadcasts=1
#
#If the returned line does not have a value of “1”, a line is not returned, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040380 not implemented"

