---
# STIG: RHEL-07-040070 - The cn_map file must be owned by root.
# description: Without mapping the certificate used to authenticate to the user account, the ability to determine the identity of the individual user or group will not be available for forensic analysis.
# severity: 'medium'
# checkid: 'C-RHEL-07-040070_chk'
# fixid: 'F-RHEL-07-040070_fix'
# version: 'RHEL-07-040070'
# ruleid: 'RHEL-07-040070_rule'
# fixtext: 'Configure the operating system to protect the file that maps the authenticated identity to the user or group account for PKI-based authentication by setting the owner on the cn_map file to root with the following command:
#
## chown root /etc/pam_pkcs11/cn_map'
# checktext: 'Verify the operating system protects the file that maps the authenticated identity to the user or group account for PKI–based authentication.
#
#Check the owner on the cn_map file with the following command:
#
## ls –al /etc/pam_pkcs11/cn_map
#–rw––––––– 1 root root 1294 Apr 22 17:22 /etc/pam_pkcs11/cn_map
#
#If the cn_map file has an owner other than root, this is a finding.'

- debug: msg="rhel_07_040070 not implemented"

