---
# STIG: RHEL-07-040260 - All networked systems must have SSH installed.
# description: Without protection of the transmitted information, confidentiality and integrity may be compromised because unprotected communications can be intercepted and either read or altered.   This requirement applies to both internal and external networks and all types of information system components from which information can be transmitted (e.g., servers, mobile devices, notebook computers, printers, copiers, scanners, and facsimile machines). Communication paths outside the physical protection of a controlled boundary are exposed to the possibility of interception and modification.   Protecting the confidentiality and integrity of organizational information can be accomplished by physical means (e.g., employing physical distribution systems) or by logical means (e.g., employing cryptographic techniques). If physical means of protection are employed, logical means (cryptography) do not have to be employed, and vice versa.  Satisfies: SRG-OS-000423-GPOS-00187, SRG-OS-000423-GPOS-00188, SRG-OS-000423-GPOS-00189, SRG-OS-000423-GPOS-00190
# severity: 'medium'
# checkid: 'C-RHEL-07-040260_chk'
# fixid: 'F-RHEL-07-040260_fix'
# version: 'RHEL-07-040260'
# ruleid: 'RHEL-07-040260_rule'
# fixtext: 'Install SSH packages onto the host with the following commands:
#
## yum install openssh-clients.x86_64
## yum install openssh-server.x86_64
#
#Note: 32-bit versions will require different packages.'
# checktext: 'Check to see if sshd is installed with the following command:
#
## yum list installed | grep ssh
#libssh2.x86_64                           1.4.3-8.el7               @anaconda/7.1
#openssh.x86_64                           6.6.1p1-11.el7            @anaconda/7.1
#openssh-clients.x86_64                   6.6.1p1-11.el7            @anaconda/7.1
#openssh-server.x86_64                    6.6.1p1-11.el7            @anaconda/7.1
#
#If the “SSH server” package is not installed, this is a finding.
#
#If the “SSH client” package is not installed, this is a finding.'

- debug: msg="rhel_07_040260 not implemented"

