---
# STIG: RHEL-07-030523 - The operating system must generate audit records containing the full-text recording of modifications to sudo configuration files.
# description: Reconstruction of harmful events or forensic analysis is not possible if audit records do not contain enough information.  At a minimum, the organization must audit the full-text recording of privileged access commands. The organization must maintain audit trails in sufficient detail to reconstruct events to determine the cause and impact of compromise.  Satisfies: SRG-OS-000037-GPOS-00015, SRG-OS-000042-GPOS-00020, SRG-OS-000392-GPOS-00172, SRG-OS-000462-GPOS-00206, SRG-OS-000471-GPOS-00215
# severity: 'medium'
# checkid: 'C-RHEL-07-030523_chk'
# fixid: 'F-RHEL-07-030523_fix'
# version: 'RHEL-07-030523'
# ruleid: 'RHEL-07-030523_rule'
# fixtext: 'Configure the operating system to generate audit records containing the full-text recording of modifications to sudo configuration files. 
#
#Add or update the following rule in /etc/audit/rules.d/audit.rules: 
#
#-w /etc/sudoers -p wa -k privileged-actions
#
#-w /etc/sudoers.d/ -p wa -k privileged-actions'
# checktext: 'Verify the operating system generates audit records containing the full-text recording of modifications to sudo configuration files. 
#
#Check for modification of the following files being audited by performing the following commands to check the file system rules in /etc/audit/rules.d/audit.rules: 
#
## grep -i /etc/sudoers /etc/audit/rules.d/audit.rules
#
#-w /etc/sudoers -p wa -k privileged-actions
#
## grep -i /etc/sudoers.d/etc/audit/rules.d/audit.rules
#
#-w /etc/sudoers.d/ -p wa -k privileged-actions
#
#If the command does not return output that does not match the examples, this is a finding.'

- debug: msg="rhel_07_030523 not implemented"

