---
# STIG: RHEL-07-040060 - The cn_map file must have mode 0644 or less permissive.
# description: Without mapping the certificate used to authenticate to the user account, the ability to determine the identity of the individual user or group will not be available for forensic analysis.
# severity: 'medium'
# checkid: 'C-RHEL-07-040060_chk'
# fixid: 'F-RHEL-07-040060_fix'
# version: 'RHEL-07-040060'
# ruleid: 'RHEL-07-040060_rule'
# fixtext: 'Configure the operating system to protect the file that maps the authenticated identity to the user or group account for PKI-based authentication by setting the mode on the cn_map file to “0644” with the following command:
#
## chmod 0644 /etc/pam_pkcs11/cn_map'
# checktext: 'Verify the operating system protects the file that maps the authenticated identity to the user or group account for PKI–based authentication.
#
#Check the mode on the cn_map file with the following command:
#
## ls –al /etc/pam_pkcs11/cn_map
#–rw––––––– 1 root root 1294 Apr 22 17:22 /etc/pam_pkcs11/cn_map
#
#If the cn_map file has a mode more permissive than “0644”, this is a finding.'

- debug: msg="rhel_07_040060 not implemented"

