---
# STIG: RHEL-07-010442 - The operating system must not allow a non-certificate trusted host SSH logon to the system.
# description: Failure to restrict system access to authenticated users negatively impacts operating system security.
# severity: 'medium'
# checkid: 'C-RHEL-07-010442_chk'
# fixid: 'F-RHEL-07-010442_fix'
# version: 'RHEL-07-010442'
# ruleid: 'RHEL-07-010442_rule'
# fixtext: 'Configure the operating system to not allow a non-certificate trusted host SSH logon to the system.
#
#Edit the /etc/ssh/sshd_config file to uncomment or add the line for “HostbasedAuthentication” keyword and set the value to “no”:
#
#HostbasedAuthentication no'
# checktext: 'Verify the operating system does not allow a non-certificate trusted host SSH logon to the system.
#
#Check for the value of the HostbasedAuthentication keyword with the following command:
#
## grep -i hostbasedauthentication /etc/ssh/sshd_config
#HostbasedAuthentication no
#
#If the “HostbasedAuthentication” keyword is not set to “no”, is missing, or is commented out, this is a finding.'

- debug: msg="rhel_07_010442 not implemented"

