---
# STIG: RHEL-07-020940 - All system device files must be correctly labeled to prevent unauthorized modification.
# description: If an unauthorized or modified device is allowed to exist on the system, there is the possibility the system may perform unintended or unauthorized operations.
# severity: 'medium'
# checkid: 'C-RHEL-07-020940_chk'
# fixid: 'F-RHEL-07-020940_fix'
# version: 'RHEL-07-020940'
# ruleid: 'RHEL-07-020940_rule'
# fixtext: 'Run the following command to determine which package owns the device file:
#
## rpm -qf <filename>
#
#The package can be reinstalled from a yum repository using the command:
#
## sudo yum reinstall <packagename>
#
#Alternatively, the package can be reinstalled from trusted media using the command:
#
## sudo rpm -Uvh <packagename>'
# checktext: 'Verify that all system device files are correctly labeled to prevent unauthorized modification.
#
#List all device files on the system that are incorrectly labeled with the following commands:
#
#Note: Device files are normally found under “/dev”, but applications may place device files in other directories, necessitating a search of the entire system.
#
##find /dev -context *:device_t:* \( -type c -o -type b \) -printf "%p %Z\n"
#
##find /dev -context *:unlabeled_t:* \( -type c -o -type b \) -printf "%p %Z\n"
#
#If there is output from either of these commands, this is a finding.'

- debug: msg="rhel_07_020940 not implemented"

