---
# STIG: RHEL-07-021011 - Files systems that are used with removable media must be mounted to prevent files with the setuid and setgid bit set from being executed.
# description: The "nosuid" mount option causes the system to not execute setuid and setgid files with owner privileges. This option must be used for mounting any file system not containing approved setuid and setguid files. Executing files from untrusted file systems increases the opportunity for unprivileged users to attain unauthorized administrative access.
# severity: 'medium'
# checkid: 'C-RHEL-07-021011_chk'
# fixid: 'F-RHEL-07-021011_fix'
# version: 'RHEL-07-021011'
# ruleid: 'RHEL-07-021011_rule'
# fixtext: 'Configure the “/etc/fstab” to use the “nosuid” option on file systems that are associated with removable media.'
# checktext: 'Verify file systems that are used for removable media are mounted with the “nosetuid” option.
#
#Check the file systems that are mounted at boot time with the following command:
#
## more /etc/fstab
#
#UUID=2bc871e4-e2a3-4f29-9ece-3be60c835222     /mnt/usbflash      vfat   noauto,owner,ro,nosuid                        0 0
#
#If a file system found in “/etc/fstab” refers to removable media and it does not have the “nosetuid” option set, this is a finding.'

- debug: msg="rhel_07_021011 not implemented"

