---
# STIG: RHEL-07-040580 - SNMP community strings must be changed from the default.
# description: Whether active or not, default Simple Network Management Protocol (SNMP) community strings must be changed to maintain security. If the service is running with the default authenticators, anyone can gather data about the system and the network and use the information to potentially compromise the integrity of the system or network(s). It is highly recommended that SNMP version 3 user authentication and message encryption be used in place of the version 2 community strings.
# severity: 'high'
# checkid: 'C-RHEL-07-040580_chk'
# fixid: 'F-RHEL-07-040580_fix'
# version: 'RHEL-07-040580'
# ruleid: 'RHEL-07-040580_rule'
# fixtext: 'If the “/etc/snmp/snmpd.conf” file exists, modify any lines that contain a community string of public or private to another string.'
# checktext: 'Verify that a system using SNMP is not using default community strings.
#
#Check to see if the “/etc/snmp/snmpd.conf” file exists with the following command:
#
## ls -al /etc/snmp/snmpd.conf
# -rw-------   1 root root      52640 Mar 12 11:08 snmpd.conf
#
#If the file does not exist, this is Not Applicable.
#
#If the file does exist, check for the default community strings with the following commands:
#
## grep public /etc/snmp/snmpd.conf
## grep private /etc/snmp/snmpd.conf
#
#If either of these command returns any output, this is a finding.'

- debug: msg="rhel_07_040580 not implemented"

