---
# STIG: RHEL-07-040351 - The system must not forward Internet Protocol version 4 (IPv4) source-routed packets by default.
# description: Source-routed packets allow the source of the packet to suggest that routers forward the packet along a different path than configured on the router, which can be used to bypass network security measures. This requirement applies only to the forwarding of source-routed traffic, such as when IPv4 forwarding is enabled and the system is functioning as a router.
# severity: 'medium'
# checkid: 'C-RHEL-07-040351_chk'
# fixid: 'F-RHEL-07-040351_fix'
# version: 'RHEL-07-040351'
# ruleid: 'RHEL-07-040351_rule'
# fixtext: 'Set the system to the required kernel parameter by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):
#
#net.ipv4.conf.default.accept_source_route = 0'
# checktext: 'Verify the system does not accept IPv4 source-routed packets by default.
#
#Check the value of the accept source route variable with the following command:
#
## /sbin/sysctl -a | grep  net.ipv4.conf.default.accept_source_route
#net.ipv4.conf.default.accept_source_route=0
#
#If the returned line does not have a value of “0”, a line is not returned, or the returned line is commented out, this is a finding.'

- debug: msg="rhel_07_040351 not implemented"

