---
# STIG: RHEL-07-040670 - The SSH daemon must not permit Kerberos authentication unless needed.
# description: Kerberos authentication for SSH is often implemented using Generic Security Service Application Program Interface (GSSAPI). If Kerberos is enabled through SSH, the SSH daemon provides a means of access to the system\'s Kerberos implementation. Vulnerabilities in the system\'s Kerberos implementation may then be subject to exploitation. To reduce the attack surface of the system, the Kerberos authentication mechanism within SSH must be disabled for systems not using this capability.
# severity: 'medium'
# checkid: 'C-RHEL-07-040670_chk'
# fixid: 'F-RHEL-07-040670_fix'
# version: 'RHEL-07-040670'
# ruleid: 'RHEL-07-040670_rule'
# fixtext: 'Uncomment the “KerberosAuthentication” keyword in /etc/ssh/sshd_config (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor) and set the value to "no":
#
#KerberosAuthentication no
#
#If Kerberos authentication is required, it must be documented, to include the location of the configuration file, with the ISSO.'
# checktext: 'Verify the SSH daemon does not permit Kerberos to authenticate passwords unless approved.
#
#Check that the SSH daemon does not permit Kerberos to authenticate passwords with the following command:
#
## grep -i kerberosauth /etc/ssh/sshd_config
#KerberosAuthentication no
#
#If the “KerberosAuthentication” keyword is missing, or is set to "yes" and is not documented with the Information System Security Officer (ISSO), or the returned line is commented out, this is a finding.'

- debug: msg="rhel_07_040670 not implemented"

