---
# STIG: RHEL-07-040310 - The system must not permit direct logons to the root account using remote access via SSH.
# description: Even though the communications channel may be encrypted, an additional layer of security is gained by extending the policy of not logging on directly as root. In addition, logging on with a user-specific account provides individual accountability of actions performed on the system.
# severity: 'medium'
# checkid: 'C-RHEL-07-040310_chk'
# fixid: 'F-RHEL-07-040310_fix'
# version: 'RHEL-07-040310'
# ruleid: 'RHEL-07-040310_rule'
# fixtext: 'Configure SSH to stop users from logging on remotely as the root user.
#
#Edit the appropriate  /etc/ssh/sshd_config file to uncomment or add the line for the PermitRootLogin keyword and set its value to “no” (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor):
#
#PermitRootLogin no'
# checktext: 'Verify remote access using SSH prevents users from logging on directly as root.
#
#Check that SSH prevents users from logging on directly as root with the following command:
#
## grep -i permitrootlogin /etc/ssh/sshd_config
#PermitRootLogin no
#
#If the “PermitRootLogin” keyword is set to “yes”, is missing, or is commented out, this is a finding.'

- debug: msg="rhel_07_040310 not implemented"

