---
# STIG: RHEL-07-040410 - The system must ignore to Internet Protocol version 4 (IPv4) Internet Control Message Protocol (ICMP) redirect messages.
# description: ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular destination. These messages modify the host\'s route table and are unauthenticated. An illicit ICMP redirect message could result in a man-in-the-middle attack.
# severity: 'medium'
# checkid: 'C-RHEL-07-040410_chk'
# fixid: 'F-RHEL-07-040410_fix'
# version: 'RHEL-07-040410'
# ruleid: 'RHEL-07-040410_rule'
# fixtext: 'Set the system to the required kernel parameter by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):
#
#net.ipv4.conf.all.accept_redirects = 0
#net.ipv4.conf.default.accept_redirects = 0'
# checktext: 'Verify the system ignores IPv4 ICMP redirect messages.
#
#Check the value of the “accept_redirects” variables with the following command:
#
## /sbin/sysctl -a | grep  \'net.ipv4.conf.*.accept_redirects\'
#net.ipv4.conf.default.accept_redirects=0
#net.ipv4.conf.all.accept_redirects=0
#
#If both of the returned line do not have a value of “0”, a line is not returned, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040410 not implemented"

