---
# STIG: RHEL-07-010073 - The operating system must initiate a session lock for the screensaver after a period of inactivity for graphical user interfaces.
# description: A session time-out lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not log out because of the temporary nature of the absence. Rather than relying on the user to manually lock their operating system session prior to vacating the vicinity, operating systems need to be able to identify when a user\'s session has idled and take action to initiate the session lock.  The session lock is implemented at the point where session activity can be determined and/or controlled.
# severity: 'medium'
# checkid: 'C-RHEL-07-010073_chk'
# fixid: 'F-RHEL-07-010073_fix'
# version: 'RHEL-07-010073'
# ruleid: 'RHEL-07-010073_rule'
# fixtext: 'Configure the operating system to initiate a session lock after a 15-minute period of inactivity for graphical user interfaces.
#
#Create a database to contain the system-wide screensaver settings (if it does not already exist) with the following command: 
#
## touch /etc/dconf/db/local.d/00-screensaver
#
#Add the setting to enable screensaver locking after 15 minutes of inactivity:
#
#[org/gnome/desktop/screensaver]
#
#idle-activation-enabled=true'
# checktext: 'Verify the operating system initiates a session lock after a 15-minute period of inactivity for graphical user interfaces. The screen program must be installed to lock sessions on the console.
#
#If it is installed, GNOME must be configured to enforce a session lock after a 15-minute delay. Check for the session lock settings with the following commands:
#
## grep -i  idle_activation_enabled /etc/dconf/db/local.d/*
#[org/gnome/desktop/screensaver]   idle-activation-enabled=true
#
#If the idle-activation-enabled not set to “true”, this is a finding.'

- debug: msg="rhel_07_010073 not implemented"

