---
# STIG: RHEL-07-040660 - The SSH daemon must not permit Generic Security Service Application Program Interface (GSSAPI) authentication unless needed.
# description: GSSAPI authentication is used to provide additional authentication mechanisms to applications. Allowing GSSAPI authentication through SSH exposes the system’s GSSAPI to remote hosts, increasing the attack surface of the system. GSSAPI authentication must be disabled unless needed.
# severity: 'medium'
# checkid: 'C-RHEL-07-040660_chk'
# fixid: 'F-RHEL-07-040660_fix'
# version: 'RHEL-07-040660'
# ruleid: 'RHEL-07-040660_rule'
# fixtext: 'Uncomment the “GSSAPIAuthentication” keyword in /etc/ssh/sshd_config (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor) and set the value to "no": 
#
#GSSAPIAuthentication no
#
#If GSSAPI authentication is required, it must be documented, to include the location of the configuration file, with the ISSO.'
# checktext: 'Verify the SSH daemon does not permit GSSAPI authentication unless approved.
#
#Check that the SSH daemon does not permit GSSAPI authentication with the following command:
#
## grep -i gssapiauth /etc/ssh/sshd_config
#GSSAPIAuthentication no
#
#If the “GSSAPIAuthentication” keyword is missing, is set to “yes” and is not documented with the Information System Security Officer (ISSO), or the returned line is commented out, this is a finding.'

- debug: msg="rhel_07_040660 not implemented"

