---
# STIG: RHEL-07-040700 - The SSH daemon must not allow compression or must only allow compression after successful authentication.
# description: If compression is allowed in an SSH connection prior to authentication, vulnerabilities in the compression software could result in compromise of the system from an unauthenticated connection, potentially with root privileges.
# severity: 'medium'
# checkid: 'C-RHEL-07-040700_chk'
# fixid: 'F-RHEL-07-040700_fix'
# version: 'RHEL-07-040700'
# ruleid: 'RHEL-07-040700_rule'
# fixtext: 'Uncomment the “Compression” keyword in /etc/ssh/sshd_config (this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor) on the system and set the value to "delayed" or "no":
#
#Compression no'
# checktext: 'Verify the SSH daemon performs compression after a user successfully authenticates.
#
#Check that the SSH daemon performs compression after a user successfully authenticates with the following command:
#
## grep -i compression /etc/ssh/sshd_config
#Compression delayed
#
#If the “Compression” keyword is set to “yes”, is missing, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040700 not implemented"

