---
# STIG: RHEL-07-010260 - The system must not have accounts configured with blank or null passwords.
# description: If an account has an empty password, anyone could log on and run commands with the privileges of that account. Accounts with empty passwords should never be used in operational environments.
# severity: 'high'
# checkid: 'C-RHEL-07-010260_chk'
# fixid: 'F-RHEL-07-010260_fix'
# version: 'RHEL-07-010260'
# ruleid: 'RHEL-07-010260_rule'
# fixtext: 'If an account is configured for password authentication but does not have an assigned password, it may be possible to log on to the account without authenticating.
#
#Remove any instances of the "nullok" option in "/etc/pam.d/system-auth" to prevent logons with empty passwords.'
# checktext: 'To verify that null passwords cannot be used, run the following command: 
#
## grep nullok /etc/pam.d/system-auth
#
#If this produces any output, it may be possible to log on with accounts with empty passwords.
#
#If null passwords can be used, this is a finding.'

- debug: msg="rhel_07_010260 not implemented"

