---
# STIG: RHEL-07-040480 - The system must be configured to prevent unrestricted mail relaying.
# description: If unrestricted mail relaying is permitted, unauthorized senders could use this host as a mail relay for the purpose of sending spam or other unauthorized activity.
# severity: 'medium'
# checkid: 'C-RHEL-07-040480_chk'
# fixid: 'F-RHEL-07-040480_fix'
# version: 'RHEL-07-040480'
# ruleid: 'RHEL-07-040480_rule'
# fixtext: 'If “postfix” is installed, modify the “/etc/postfix/main.cf” file to restrict client connections to the local network with the following configuration line:
#
#smtpd_client_restrictions = permit_mynetworks, reject'
# checktext: 'Verify the system is configured to prevent unrestricted mail relaying.
#
#Determine if "postfix" or "sendmail" are installed with the following commands:
#
## yum list installed | grep postfix
#postfix-2.6.6-6.el7.x86_64.rpm 
## yum list installed | grep sendmail
#
#If neither are installed, this is Not Applicable.
#
#If postfix is installed, determine if it is configured to reject connections from unknown or untrusted networks with the following command:
#
## grep smtpd_client_restrictions /etc/postfix/main.cf
#smtpd_client_restrictions = permit_mynetworks, reject
#
#If the “smtpd_client_restrictions” parameter contains any entries other than "permit_mynetworks" and "reject", this is a finding.'

- debug: msg="rhel_07_040480 not implemented"

