---
# STIG: RHEL-07-020660 - All local interactive user home directories must be owned by their respective users.
# description: If a local interactive user does not own their home directory, unauthorized users could access or modify the user\'s files, and the users may not be able to access their own files.
# severity: 'medium'
# checkid: 'C-RHEL-07-020660_chk'
# fixid: 'F-RHEL-07-020660_fix'
# version: 'RHEL-07-020660'
# ruleid: 'RHEL-07-020660_rule'
# fixtext: 'Change the owner of a local interactive user’s home directories to that owner. To change the owner of a local interactive user’s home directory use the following command:
#
#Note: The example will be for the user smithj, who has a home directory of “/home/smithj”.
#
## chown smithj /home/smithj'
# checktext: 'Verify the assigned home directory of all local interactive users is owned by that user.
#
#Check the home directory assignment for all non-privileged users on the system with the following command:
#
## cut -d: -f 1,3 /etc/passwd | egrep ":[1-4][0-9]{2}$|:[0-9]{1,2}$"
#smithj /home/smithj
#
#Note: This may miss local interactive users that have been assigned a privileged User Identifier (UID). Evidence of interactive use may be obtained from a number of log files containing system logon information.
#
#Check the owner of all local interactive users home directories with the following command:
#
## ls -al <users home directory>
#drwxr-x---  1 smithj users        860 Nov 28 06:43 smithj
#
#If user home directory referenced in “/etc/passwd” is not owned by that user, this is a finding.'

- debug: msg="rhel_07_020660 not implemented"

