---
# STIG: RHEL-07-040860 - The system must not forward IPv6 source-routed packets.
# description: Source-routed packets allow the source of the packet to suggest that routers forward the packet along a different path than configured on the router, which can be used to bypass network security measures. This requirement applies only to the forwarding of source-routed traffic, such as when IPv6 forwarding is enabled and the system is functioning as a router.
# severity: 'medium'
# checkid: 'C-RHEL-07-040860_chk'
# fixid: 'F-RHEL-07-040860_fix'
# version: 'RHEL-07-040860'
# ruleid: 'RHEL-07-040860_rule'
# fixtext: 'Set the system to the required kernel parameter, if IPv6 is enabled, by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):
#
#net.ipv6.conf.all.accept_source_route = 0'
# checktext: 'Verify the system does not accept IPv6 source-routed packets.
#
#Note: If IPv6 is not enabled, the key will not exist, and this is not a finding.
#
#Check the value of the accept source route variable with the following command:
#
## /sbin/sysctl -a | grep  net.ipv6.conf.all.accept_source_route
#net.ipv6.conf.all.accept_source_route=0
#
#If the returned lines do not have a value of “0”, a line is not returned, or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040860 not implemented"

