---
# STIG: RHEL-07-040620 - The SSH daemon must be configured to only use Message Authentication Codes (MACs) employing FIPS 140-2 approved cryptographic hash algorithms.
# description: DoD information systems are required to use FIPS 140-2 approved cryptographic hash functions. The only SSHv2 hash algorithm meeting this requirement is SHA.
# severity: 'medium'
# checkid: 'C-RHEL-07-040620_chk'
# fixid: 'F-RHEL-07-040620_fix'
# version: 'RHEL-07-040620'
# ruleid: 'RHEL-07-040620_rule'
# fixtext: 'Edit the /etc/ssh/sshd_config file to uncomment or add the line for the MACs keyword and set its value to “hmac-sha2-256” and/or “hmac-sha2-512 “(this file may be named differently or be in a different location if using a version of SSH that is provided by a third-party vendor):
#
#MACs hmac-sha2-256,hmac-sha2-512'
# checktext: 'Verify the SSH daemon is configured to only use MACs employing FIPS 140-2 approved ciphers.
#
#Note: If RHEL-07-021280 is a finding, this is automatically a finding as the system cannot implement FIPS 140-2 approved cryptographic algorithms and hashes.
#
#Check that the SSH daemon is configured to only use MACs employing FIPS 140-2 approved ciphers with the following command:
#
## grep -i macs /etc/ssh/sshd_config
#MACs hmac-sha2-256,hmac-sha2-512
#
#If any ciphers other than “hmac-sha2-256” or “hmac-sha2-512” are listed or the retuned line is commented out, this is a finding.'

- debug: msg="rhel_07_040620 not implemented"

