---
# STIG: RHEL-07-030340 - The audit system must take appropriate action when the audit storage volume is full.
# description: Taking appropriate action in case of a filled audit storage volume will minimize the possibility of losing audit records.
# severity: 'medium'
# checkid: 'C-RHEL-07-030340_chk'
# fixid: 'F-RHEL-07-030340_fix'
# version: 'RHEL-07-030340'
# ruleid: 'RHEL-07-030340_rule'
# fixtext: 'Configure the operating system to off-load audit records onto a different system or media from the system being audited.
#
#Uncomment or edit the "disk_full_action" option in /etc/audisp/audisp-remote.conf and set it to syslog, single, or halt, such as the following line:
#
#disk_full_action = single
#
#Uncomment the network_failure_action option in /etc/audisp/audisp-remote.conf and set it to syslog, single, or halt.'
# checktext: 'Verify the action the operating system takes if the disk the audit records are written to becomes full.
#
#To determine the action that takes place if the disk is full on the remote server, use the following command:
#
## grep -i disk_full_action /etc/audisp/audisp-remote.conf
#disk_full_action = single
#
#To determine the action that takes place if the network connection fails, use the following command:
#
## grep -i network_failure_action /etc/audisp/audisp-remote.conf
#network_failure_action = stop
#
#If the value of the “network_failure_action” option is not “syslog”, “single”, or “halt”, or the line is commented out, this is a finding.
#
#If the value of the “disk_full_action” option is not "syslog", "single", or "halt", or the line is commented out, this is a finding.'

- debug: msg="rhel_07_030340 not implemented"

